// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  custom_slice: defineAsyncComponent(() => import("./CustomSlice/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  image_cards: defineAsyncComponent(() => import("./ImageCards/index.vue")),
  quote: defineAsyncComponent(() => import("./Quote/index.vue")),
  tab_panel: defineAsyncComponent(() => import("./TabPanel/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
  text_with_image: defineAsyncComponent(
    () => import("./TextWithImage/index.vue"),
  ),
});
